package:
  name: tfbs-footprinting3
  version: "0.1.1"

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.9,<3.13
    - pip
    - setuptools >=64
  run:
    - python >=3.9,<3.13
    - numpy
    - matplotlib
    - biopython
    - msgpack-python
    - pandas
    - httplib2

about:
  home: https://github.com/thirtysix/TFBS_footprinting3
  license: MIT
  license_family: MIT
  summary: "Tool for identifying conserved TFBSs in vertebrate species."

extra:
  recipe-maintainers:
    - thirtysix

